Added work and about me sections to index.html
c00p75/Portfolio-setup-and-mobile-first pull request #2
Opened 2022-10-28 21:17 UTC by c00p75

Added work and about me sections to index.html which used grid and flexbox | aligned about me section with flexbox | used <ul> for categories in about myself and Work sections | Added necessary image files

2022-10-28 21:55 UTC, bienvenuushindi requested changes
### Hi @c00p75 ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linter checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- **Please make sure your commit messages are limited to 80 characters.**

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-28 21:55 UTC, bienvenuushindi commented on index.html
> +							<p class="work_item_header">Multi-Post Stories</p>
:red_circle: Please make sure you use `hx` tag for All the project card headers. A `p` tag is not semantically appropriate. Please change it to a heading

2022-10-28 21:55 UTC, bienvenuushindi commented on index.html
> +							<p class="work_item_header">Tonic</p>
:red_circle: This should be a `hx` tag. A `p` tag is not semantically appropriate. Please change it to a heading

2022-10-28 21:55 UTC, bienvenuushindi commented on index.html
> +						</div>
- :red_circle: The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") should be wrapped inside a list ul and each item of them in a li tag. Please replace the `div` container with a `ul` container

2022-10-28 21:55 UTC, bienvenuushindi commented on index.html
> +								<p>LET'S CONNECT</p>
:red_circle: LET'S CONNECT is a title, It should be in a header tag hx. Please make sure you use a header tag hx here

2022-10-28 22:25 UTC, bienvenuushindi reviewed
**[OPTIONAL] Please in the future project make sure your commit messages are limited to 80 characters.**

2022-10-29 06:45 UTC, c00p75 commented
Used <h2> for project card headers and 'LET'S CONNECT' and wrapped project technologies in list

2022-10-29 06:51 UTC, OyePriscilla approved these changes
# Hi @c00p75  😄 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
You documented your work professionally. ✔
GitHub flow is used correctly. ✔
All linter checks are ok. ✔


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @oyepriscilla in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 11:26 UTC, merged